version: '3.8'

services:
  flextts:
    container_name: flextts  # Fixed container name
    build: .
    ports:
      - "6969:6969"
    volumes:
      - .:/app  # Mount the entire app directory
      - ./data:/app/data  # Keep persistent data separate
      - ./static:/app/static  # Keep static files separate
    environment:
      - FLASK_APP=flextts.py
      - FLASK_DEBUG=1  # Enable Flask debug mode for auto-reload
      - DEFAULT_LANGUAGE=en # Default language for text-to-speech
      - DEFAULT_SPEAKER=Donald_Trump # Default speaker for text-to-speech
      - DOCKER_PORT=6969 # External port for URL generation
    restart: unless-stopped  # Automatically restart container unless manually stopped
