services:
  flextts:
    container_name: flextts
    build:
      context: .
      dockerfile: Dockerfile.cuda.ubuntu22.04
    runtime: nvidia
    ports:
      - "6969:6969"
    volumes:
      - .:/app  # Mount the entire app directory
      - ./data:/app/data  # Keep persistent data separate
      - ./static:/app/static  # Keep static files separate
    environment:
      - FLASK_APP=/app/flextts.py  # Full path to the Flask app
      - FLASK_DEBUG=1  # Enable Flask debug mode for auto-reload
      - APP_PATH=/app  # Set app path for container
      - DEFAULT_LANGUAGE=en # Default language for text-to-speech
      - DEFAULT_SPEAKER=donald_trump # Default speaker for text-to-speech
      - DOCKER_PORT=6969 # External port for URL generation
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped  # Automatically restart container unless manually stopped
