services:
  flextts:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
